orbs:
  architect: giantswarm/architect@0.4.5
version: 2.1
jobs:
  build:
    machine: true
    steps:
    - checkout

    - run: |
        wget -q $(curl -sS -H "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/tags/v1.0.0 | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
        chmod +x ./architect
        ./architect version
    - run: ./architect build
    - persist_to_workspace:
        root: .
        paths:
        - ./etcd-backup
        - ./architect
  deploy:
    machine: true
    steps:
    - checkout
    - attach_workspace:
        at: .
    - deploy:
        command: |
            ./architect deploy

workflows:
  build_e2e:
    jobs:
      - build
      - architect/push-to-docker-legacy:
          name: push-etcd-backup-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/etcd-backup"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          # Push to Aliyun should execute for non-master branches only once manually approved.
          requires:
            - build
      - deploy:
          name: deploy
          requires:
            - push-etcd-backup-to-aliyun
          filters:
            branches:
              only: master
