apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: etcd-backup-pull-secret
  namespace: kube-system
data:
  .dockerconfigjson: {{ .Values.Installation.V1.Secret.Registry.PullSecret.DockerConfigJSON | b64enc | quote }}
