resource:
  default:
    name: {{ .Release.Name }}
    namespace: "kube-system"
  psp:
    name: {{ .Release.Name }}-psp
  pullSecret:
    name: {{ .Release.Name }}-pull-secret

pod:
  user:
    id: 0
  group:
    id: 1000
